---
- hosts: default
  become: true
  tasks:
    - copy:
        src: /var/lib/jenkins/workspace/leafer/scripts/
        dest: /tmp

    - name: Compress sql file
      command: bzip2 -f /tmp/leafer.sql

    - name: Restore database
      mysql_db:
        name: my_db
        login_user: root
        login_password: root
        state: import
        target: /tmp/leafer.sql.bz2

#    - name: Stop tomcat7 service
#      service:
#        name: tomcat7
#        state: stoped

    - copy:
        src: /var/lib/jenkins/workspace/leafer/target/leafer.jar
        dest: /tmp

    - name: start project
      command: java -jar /tmp/leafer.jar &


#    - name: Start tomcat7 service
#      service:
#        name: tomcat7
#        state: started
