---
- hosts: default
  become: true
  tasks:
    - copy:
        src: /var/lib/jenkins/workspace/leafer/scripts/
        dest: /tmp

    - name: Compress sql file
      command: bzip2 -f /tmp/leafer.sql

    - name: Restore database
      mysql_db:
        name: my_db
        state: import
        target: /tmp/leafer.sql.bz2

    - copy:
        src: /var/lib/jenkins/workspace/leafer/target
        dest: /tmp

    - name: run project with package
      command: java -jar /tmp/target/leafer-0.1.0.jar &

