---
- hosts: default
  become: true
  tasks:
    - copy:
        src: /var/lib/jenkins/workspace/leafer/scripts/
        dest: /tmp

    - file:
        path: /tmp/db_config.sh
        mode: 0755

    - name: DB migration
      shell: /tmp/db_config.sh

    - copy:
        src: /var/lib/jenkins/workspace/leafer/target/leafer-1.5.3.RELEASE.jar
        dest: /tmp

    - name: start project
      command: java -jar /tmp/leafer-1.5.3.RELEASE.jar &
