pipeline{
  agent any

  stages{
    stage('Build'){
      steps{
        step{
          cd /var/lib/jenkins/workspace/leafer
        }
        step{
          mvn clean install
        }
      }
    }

    stage('DB_Migration'){
      steps{
        sh '/var/lib/jenkins/workspace/leafer/scripts/db_config.sh'
      }
    }

    stage('Deploy'){
      steps{
        sh '/var/lib/jenkins/workspace/leafer/scripts/deploy.sh'
      }
    }
  }
}