pipeline{
  agent any

  stages{
    stage('Build'){
      steps{
          sh 'cd /var/lib/jenkins/workspace/leafer'
          sh 'mvn clean install'
      }
    }

    stage('Deploy'){
      steps{
        sh 'ansible-playbook deploy.yml'
      }
    }
  }
}